const mongoose=require("mongoose");

const orderSchema=new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            requierd:true
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true,
            defalut:"india"
        },
        pin:{
            type:Number,
            required:true
        },
        phoneno:{
            type:Number,
            required:true
        }

    },
    orderItems:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            product:{
                type:mongoose.Schema.ObjectId,
                ref:"Product",
                requried:true
            }
        }
    ],
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"user",
        required:true
    },
    paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        }
    },
    paidAt:{
        type:Date,
        required:true
    },
    itemPrice:{
        type:Number,
        default:0
    },
    taxPrice:{
        type:Number,
        default:0,
        required:true
    },
    shippingPrice:{
        type:Number,
        default:0
    },
    totalPrice:{
        type:Number,
        default:0
    },
    orderStatus:{
        type:String,
        default:"processing",
        requried:true
    },
    deliverdAt:Date,
    createdAt:{
        type:Date,
        default:Date.now()
    }
})
module.exports =mongoose.model("Order",orderSchema);